let div = document.querySelector("div");
const watchContainer = document.createElement("div");
div.appendChild(watchContainer);
watchContainer.classList.add("watch-container");
const passwordGenerator = document.createElement("div");
passwordGenerator.classList.add("card");
let link = document.createElement("a");
passwordGenerator.appendChild(link);
link.append("Password Generator");
link.setAttribute("href", "./password.html");
passwordGenerator.appendChild(link);
watchContainer.appendChild(passwordGenerator);
const clock = document.createElement("div");
let link2 = document.createElement("a");
link2.append("Stopwatch-Clock");
clock.appendChild(link2);
link2.setAttribute("href", "./clock-stopwatch.html");
clock.classList.add("card");
watchContainer.appendChild(clock);
// const stopWatch = document.createElement("div");
// stopWatch.classList.add("card");
// let link3 = document.createElement("a");
// link3.append("Stop Watch");
// stopWatch.appendChild(link3);
// link3.setAttribute("href", "./clock.html");
// watchContainer.appendChild(stopWatch);
